# Numpy library

In [1]:
import numpy as np

In [2]:
a = np.array([[3,4,5],[6.7, 7.8, 8.9]])
b = np.array([1,2,3], dtype='int32')
c = np.array([])

In [3]:
print(a)
print(b)
print(c)

[[3.  4.  5. ]
 [6.7 7.8 8.9]]
[1 2 3]
[]


In [75]:
eg1 = np.linspace(1,20,17,dtype='int32')
eg1

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 14, 15, 16, 17, 18, 20],
      dtype=int32)

In [6]:
# get dimensions of array
print(a.ndim)
print(b.ndim)
print(c.ndim)

2
1
1


In [7]:
# get datatypes of array
print(a.dtype)
print(b.dtype)
print(c.dtype)

float64
int32
float64


In [8]:
# get shapes of array row,column
print(a.shape)
print(b.shape)
print(c.shape)

(2, 3)
(3,)
(0,)


In [9]:
#get size of array and itemsize
print(a.size)
print(b.size)
print(c.size)
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

6
3
0
8
4
8


Notice total size = no of bytes

In [10]:
a.size * a.itemsize

48

In [11]:
a.nbytes

48

## Accessing/ Changing spec. element, rows, columns

In [12]:
a= np.array([[1,2,3,4,5,6,7],[2,3,6,8,10,12,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 2  3  6  8 10 12 14]]


In [13]:
 # any element
print(a[1,6])
a[1,6]

14


np.int64(14)

In [14]:
# any row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# any column
a[:, 5]

array([ 6, 12])

In [16]:
a[0,2:5:2]

array([3, 5])

In [17]:
a[0,5] = 50
a

array([[ 1,  2,  3,  4,  5, 50,  7],
       [ 2,  3,  6,  8, 10, 12, 14]])

for any bigger matrices

In [18]:
threeD = np.array([[[2,3,5],[3,4,6]],[[4,6,5],[7,9,8]]])
print(threeD)
print(threeD[0,0,1])

[[[2 3 5]
  [3 4 6]]

 [[4 6 5]
  [7 9 8]]]
3


## Initializing different arrays

In [19]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [21]:
np.full((2,2),69,dtype='int32')

array([[69, 69],
       [69, 69]], dtype=int32)

In [22]:
np.full_like(a,69)

array([[69, 69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69, 69]])

In [23]:
np.random.rand(4,2)

array([[0.51635394, 0.50732003],
       [0.14031681, 0.16185916],
       [0.0676291 , 0.59464534],
       [0.21351754, 0.6929196 ]])

In [24]:
np.random.randint(2,5,(3,3))

array([[4, 2, 3],
       [3, 4, 4],
       [3, 4, 4]], dtype=int32)

In [25]:
np.identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [26]:
c= np.array([[3,3,6]])
d= np.repeat(c,3,axis = 0)
d

array([[3, 3, 6],
       [3, 3, 6],
       [3, 3, 6]])

In [27]:
p1 = np.ones((5,5), dtype="int64")
p1[1:4,1:4] = 0
p1[2,2] = 9
p1

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

### properly copying arrays

In [28]:
a = np.array([2,2,2])
b = a #wrong
b[1]=20
a


array([ 2, 20,  2])

In [29]:
a = np.array([2,2,2])
b = a.copy() #right
b[1]=20
print(a,b)

[2 2 2] [ 2 20  2]


## Mathematical operations

In [30]:
a = np.array([4,5,6,90])
a

array([ 4,  5,  6, 90])

In [31]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[ 6  7  8 92]
[ 2  3  4 88]
[  8  10  12 180]
[ 2.   2.5  3.  45. ]


In [32]:
b =np.array([3,6,9,12])
print(a+b)

[  7  11  15 102]


In [33]:
a ** 2

array([  16,   25,   36, 8100])

In [34]:
print(np.sin(a))
print(np.cos(a))

[-0.7568025  -0.95892427 -0.2794155   0.89399666]
[-0.65364362  0.28366219  0.96017029 -0.44807362]


## Linear Algebra

In [35]:
# Matrix Multiplications
a = np.full((2,3),4)
b = np.array([[5,6],[7,8],[9,10]])
c = np.linalg.matmul(a,b)
print(c)

[[84 96]
 [84 96]]


In [36]:
# Finding determinats
d = np.random.randint(2,6,(3,3))
print(d)
print(np.linalg.det(d))

[[3 3 5]
 [5 4 2]
 [4 2 5]]
-32.999999999999986


In [37]:
# Solving equations:
# eqn1 : 2x + 3y = 7
# eqn2 : 3x + 5y = 5
a = np.array([[2,3],[3,5]])
b = np.array([7,5])
print(np.linalg.solve(a,b))

[ 20. -11.]


In [38]:
# Inverse of a matrix
print(np.linalg.inv(a))

[[ 5. -3.]
 [-3.  2.]]


#### Vectors

In [39]:
v1 = np.array([2,4,5])
v2 = np.array([4,5,8])

In [40]:
# Dot product 
print(np.vdot(v1,v2)) # or np.vecdot(*,*)

68


In [41]:
#eigen values for any matrix
v1 = np.full((3,3),2)
print(np.linalg.eigh(a))
print(np.linalg.eigvals(a))
print(np.linalg.eigvalsh(a)) # for complex Hermitian or real symmetric matrices


EighResult(eigenvalues=array([0.14589803, 6.85410197]), eigenvectors=array([[-0.85065081,  0.52573111],
       [ 0.52573111,  0.85065081]]))
[0.14589803 6.85410197]
[0.14589803 6.85410197]


## Statistics

In [42]:
stats = np.array([[3,6,7],
                  [2,8,4],
                  [4,5,7]])

In [43]:
# min/ max
print(np.min(stats))
print(np.max(stats))
print(np.min(stats,axis = 0))
print(np.min(stats,axis = 1))

2
8
[2 5 4]
[3 2 4]


In [44]:
print(np.sum(stats,axis=0))
#prod- product 
# mean
# std- standard deviation
# var- variance
# argmin, argmax

[ 9 19 18]


#### Reorganizing arrays

In [45]:
# Reshaping arrays
v1 = np.array([[2,3,4,5],
               [5,6,7,8]])
v2 = v1.reshape(1,8) #(8,1),(2,2,2),(4,2),(2,4),....
print(v2)

[[2 3 4 5 5 6 7 8]]


In [46]:
#stacking arrays:
v1 = np.array([[2,3],
               [5,6]])
v2 = np.array([[3,6],
               [7,8]])
print(np.vstack((v1,v2)))
print(np.hstack((v1,v2)))

[[2 3]
 [5 6]
 [3 6]
 [7 8]]
[[2 3 3 6]
 [5 6 7 8]]


## Miscellaneous

In [67]:
#load data from a file in forms of matrices
file1 = np.genfromtxt('data_sheet1.txt', delimiter=',')
file1 = file1.astype('int32')
print(file1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


### boolean masking and advanced indexing

In [52]:
file1 < 10

array([[ True,  True,  True,  True,  True, False, False, False],
       [False, False, False,  True,  True,  True, False, False],
       [ True,  True,  True,  True, False, False, False,  True]])

In [53]:
file1[file1 < 10]

array([1, 2, 4, 5, 6, 6, 8, 9, 5, 8, 9, 0, 4], dtype=int32)

In [54]:
np.all(file1<10, axis= 0)

array([False, False, False,  True, False, False, False, False])

In [57]:
file1[(file1 >10) & (file1<100)]

array([80, 99, 34, 24, 67, 45, 23, 67, 30, 40, 50], dtype=int32)

In [62]:
file1[~(file1 >10) & (file1<100)] #         ~ = not

array([1, 2, 4, 5, 6, 6, 8, 9, 5, 8, 9, 0, 4], dtype=int32)

In [71]:
print(file1[[0,4,5],3:])


[[ 4  5]
 [24 25]
 [29 30]]
